name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mac:
    name: macOS
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.9.1
      with:
        bazelisk-cache: true
      # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
      # Share repository cache between workflows.
        repository-cache: true
    - uses: swift-actions/setup-swift@v2
      with:
          swift-version: "6.0.0"

    - name: Run build
      run: bazel build //Labelo:Labelo
          
    - name: Run tests
      run: bazel test //LabeloTests:LabeloTests 
