name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mac:
    name: ci
    runs-on: macos-15

    env:
      BUILD_BUDDY_API_KEY: ${{ secrets.BUILD_BUDDY_API_KEY }}

    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.9.1
      with:
        bazelisk-cache: true
      # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
      # Share repository cache between workflows.
        repository-cache: true

    - name: Run tests
      run: bazel test --config=CI //LabeloTests:LabeloTests

